server_connect_timeout: 5000
remote_ping_cache: -1
forge_support: false
player_limit: 300
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
timeout: 30000
log_commands: false
network_compression_threshold: 256
online_mode: false
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    motd: " &f፠ &9Lysium &f፠\n &eТру выживание только у нас, заходи!"
    address: localhost:25566
    restricted: true
  survival:
    motd: ' Survival'
    address: localhost:25567
    restructed: false
listeners:
- query_port: 25565
  motd: " &f፠ &9Lysium &f፠\n &eТру выживание только у нас, заходи!"
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 300
  tab_size: 60
  force_default_server: true
ip_forward: false
remote_ping_timeout: 5000
prevent_proxy_connections: false
groups:
  md_5:
  - admin
connection_throttle: 4000
stats: 4c1f4342-ab36-4dc6-9b9d-ab2f85f195c1
connection_throttle_limit: 3
log_pings: true
